<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPRIO1L0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPRIO1L0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPRIO1L0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPRIO1L0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPRIO1L0\App_KernelDevDebugContainer([
    'container.build_hash' => 'PRIO1L0',
    'container.build_id' => '3cb141b4',
    'container.build_time' => 1729685248,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPRIO1L0');
